### ISSUE TITLE
海外服务器使用https://api.vvhan.com/api/60s作为api会有502报错

### ISSUE THREAD

**Issue by Fantasylily** [InSnocent/Daily_News#1]
经测试，海外服务器使用https://api.vvhan.com/api/60s作为api会有502报错
HTTP Error 502: Bad Gateway
使用proxy_handler也没有用
建议使用国内服务器部署最为合适

**Comment by InSnocent** [comment]
你好，我使用的香港服务器是可以进行正常下载的，但是为了保险起见我更换了一个在测试时候境内外访问速度都还算可以的api，你可以试一下：'https://api.03c3.cn/zb/',其他部分无需更改。
不过由于该api不返回content-length，会导致下载进度条部分出现异常，可以将那块部分注释使用

**Comment by Fantasylily** [comment]
辛苦，感谢作者
