### ISSUE TITLE
TypeError: on_fullmatch() takes from 2 to 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by Ayusummer** [InSnocent/Daily_News#2]
![image](https://user-images.githubusercontent.com/59549826/182202290-c800121d-979c-4941-85d9-55a1aa9df798.png)

系统版本: ubuntu20.04LTS
python版本:3.9.1
nonebot版本:1.8.0

![image](https://user-images.githubusercontent.com/59549826/182202383-4445ac9a-d07a-4a12-b6d7-e2315164c2d1.png)

当包含多个指令时将这些指令元组作为一个参数整体可以正常运行:

![image](https://user-images.githubusercontent.com/59549826/182202678-14c1b6ed-3502-4d6a-860e-15cfd210a49a.png)

![image](https://user-images.githubusercontent.com/59549826/182203042-5096126d-9d95-4786-865f-8ec08f7e1bdd.png)

**Comment by InSnocent** [comment]
感谢，已修复
