### ISSUE TITLE
name 'callback' is not defined

### ISSUE THREAD

**Issue by Ayusummer** [InSnocent/Daily_News#3]
系统版本: ubuntu20.04LTS
python版本:3.9.1

![image](https://user-images.githubusercontent.com/59549826/182207387-784b23f1-564b-496e-87c5-e37cc04680fb.png)

翻阅文档没有找到 callback 的用法, 将其换为 None 后可以正常运行并输出结果

![image](https://user-images.githubusercontent.com/59549826/182207152-9bdd825c-7650-4daa-ad04-9156b661ed14.png)

**Comment by InSnocent** [comment]
经过排查发现是上次自定义的callback函数未删除干净，已经将其修复，谢谢
