### ISSUE TITLE
显示获取失败，请重试或联系管理员

### ISSUE THREAD

**Issue by heyuzhou12345675** [InSnocent/Daily_News#5]
![image](https://github.com/InSnocent/Daily_News/assets/43637362/b1ae33a9-d0fe-4ff2-adfd-9bd0be0f4490)
![image](https://github.com/InSnocent/Daily_News/assets/43637362/3c37b342-e51e-4038-a4e4-5c149a512994)
查看服务器上的图片好久还是十月的应该是api出问题了？

**Comment by InSnocent** [comment]
你好，是的，这个api有时候会抽风，一般在1到2日左右会恢复正常。
我正在寻找新的数据源或者考虑后续将它改成本地生成图片

**Comment by InSnocent** [comment]
你好，我已经更新了新的api，现在应该可以正常获取了

**Comment by heyuzhou12345675** [comment]
重启完以后图片没有更新

**Comment by heyuzhou12345675** [comment]
也没有发出图片
![image](https://github.com/InSnocent/Daily_News/assets/43637362/f96d3f3e-6937-4089-a42a-7ad7ab716243)
![image](https://github.com/InSnocent/Daily_News/assets/43637362/4d06d160-d26b-45b7-8e41-7df666ecb580)

**Comment by InSnocent** [comment]
删除图片后再次获取可行吗？

**Comment by InSnocent** [comment]
好的，我稍微晚一点在我的机子上测试一下

**Comment by heyuzhou12345675** [comment]
删除图片后也不行

**Comment by InSnocent** [comment]
你好，我在我这边测试了一下应该是拉取得到的，请问你那边是否有重新拉一遍这个仓库？

**Comment by heyuzhou12345675** [comment]
你好，我确实拉去了
![image](https://github.com/InSnocent/Daily_News/assets/43637362/b62e3c61-13e0-4a11-9c62-d8cba919e890)

**Comment by heyuzhou12345675** [comment]
然后删除了旧图片，发了命令依旧不行
![image](https://github.com/InSnocent/Daily_News/assets/43637362/f0e55a71-63fa-4136-835c-a165e323585a)

**Comment by InSnocent** [comment]
你好，我又重新更新了一下，可以帮我测试一下吗？非常感谢，我自己的bot现在因为风控无法登陆了

**Comment by heyuzhou12345675** [comment]
你好，我重新拉去后依旧不行= =。

**Comment by heyuzhou12345675** [comment]
![image](https://github.com/InSnocent/Daily_News/assets/43637362/aba2bbc8-aee9-40ba-bce2-c9eda3d1531d)
![image](https://github.com/InSnocent/Daily_News/assets/43637362/d3454896-cd6c-4585-befd-4c5bd3ad84be)
是我没有加载好配置文件吗？
![Uploading image.png…]()

**Comment by heyuzhou12345675** [comment]
![image](https://github.com/InSnocent/Daily_News/assets/43637362/aba2bbc8-aee9-40ba-bce2-c9eda3d1531d)
![image](https://github.com/InSnocent/Daily_News/assets/43637362/d3454896-cd6c-4585-befd-4c5bd3ad84be)
是我没有加载好配置文件吗？
![image](https://github.com/InSnocent/Daily_News/assets/43637362/8f4d9a1c-ec0c-4eb7-92c5-04991259421e)

**Comment by InSnocent** [comment]
这种情况正常，有下面那行successded to import就可以了。
运行的时候hoshino那边有回报错误信息吗，我感觉可能是api那边的图片下载不到

**Comment by heyuzhou12345675** [comment]
![image](https://github.com/InSnocent/Daily_News/assets/43637362/24bb4899-a6fd-4409-8e36-624942a2ed17)
![image](https://github.com/InSnocent/Daily_News/assets/43637362/df2b4df6-3108-46f4-a77c-985166616ce9)
log里的error.log没有想关报错，其他还有日志信息吗？

**Comment by InSnocent** [comment]
新更新的文件里面把获取文件的方式改成了异步，如果获取不到应该会回报Failed to download image才对的，
什么反应都没有我也不知道是发生了什么事（

**Comment by heyuzhou12345675** [comment]
emmmm，配置文件里配置完，还要命令加载一下吗？enable Daily_News后就好使了，我的我的

**Comment by InSnocent** [comment]
这句已经写在readme里面了![Cache_-5650c9b7932fcd72.jpg](https://github.com/InSnocent/Daily_News/assets/25134095/31f14df1-c1a9-47cc-95bd-3c7a45be0711)

**Comment by heyuzhou12345675** [comment]
![3O{~X~{Q9S7577PPPHNSS(Y](https://github.com/InSnocent/Daily_News/assets/43637362/bd553b58-527d-4ef9-8f33-ace821926843)
